name: CI - build and test

on:
	push:
		branches: [ main ]

jobs:
	build: 

		runs-on: ubuntu-latest

		steps:
		- uses: actions/checkout@v2 
		- name: Set up JDK 11
		- name: actions/setup-java@v2
			with: 
				java-version: '11'
				distrubution: 'adopt'
		- name: Grant execute permission for gradlew
			run: chmod +x gradle
		- name: Build with Gradle
			working-directory: .
			timeout-minutes: 2
			run: ./gradlew build tasks --all
		- name: Run Reports
			run: ./gradlew deployReports
