name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
   
   runs-on: ubuntu-latest
   
   steps:    
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2        
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and test
      working-directory: .
      timeout-minutes: 3
      run: ./gradlew build tasks --all
    - name: BuildWebsite
      working-directory: .
      run: ./gradlew bake
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
         branch: gh-pages # The branch the action should deploy to.
         folder: build/jbake # The folder the action should deploy.

