name: CI - build and test

on:                                
  push:
    branches: [ main ]

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:    
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2        
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew              
    - name: Build and test
      working-directory: .
      timeout-minutes: 3
      run: ./gradlew build tasks --all
    - name: Bake Website
      run: ./gradlew bake
    - name: deploy Website
      run: ./gradlew deployWebsite
